Switched TOML to properties.

diff --git a/bin/cilo b/bin/cilo
--- a/bin/cilo
+++ b/bin/cilo
@@ -71,55 +71,57 @@ showUsage() {
 PWD=`pwd`
 PROJECT_NAME="cilo" # todo: get from git or filestructure
 PIPELINE=()
+SHOW_VERSION="false"
+INTERACTIVE="true"
 VERBOSE="false"
 VVV="false"
 LOGGING="false"
-LOGGING_DIR="log/"
-SHOW_VERSION="false"
+LOGGING_DIRECTORY="log/"
 DOCKER_SOCKET="/var/run/docker.sock"
+DOCKER_REGISTRY_URL=""
+DOCKER_IMAGE_NAME="cilo"
 LIBRARY_PATH="lib/"
 LIBRARY_URL=""
-SERVER_URL=""
-INTERACTIVE="true"
-IMAGE_NAME="cilo"
-CUSTOM_REGISTRY="false"
-REGISTRY_URL=""
+CREDENTIAL_SERVER_URL=""
 
-if [ -f "~/.cilo" ]; then
-    LOGGING_DIR_HOME=`cat ~/.cilo | grep logging.directory | sed -e 's/^logging.directory=\"\(.*\)\"/\1/'`
-    LOGGING_DIR="${LOGGING_DIR_HOME:-$LOGGING_DIR}"
-    DOCKER_SOCKET_HOME=`cat ~/.cilo | grep docker.socket | sed -e 's/^docker.socket=\"\(.*\)\"/\1/'`
-    DOCKER_SOCKET="${DOCKER_SOCKET_HOME:-$DOCKER_SOCKET}"
-    REGISTRY_URL_HOME=`cat ~/.cilo | grep docker.registry | sed -e 's/^docker.registry=\"\(.*\)\"/\1/'`
-    REGISTRY_URL="${REGISTRY_URL_HOME:-$REGISTRY_URL}"
-    REGISTRY_URL_HOME=`cat ~/.cilo | grep docker.image_name | sed -e 's/^docker.image_name=\"\(.*\)\"/\1/'`
-    IMAGE_NAME="${IMAGE_NAME_HOME:-$IMAGE_NAME}"
-    LIBRARY_PATH_HOME=`cat ~/.cilo | grep library.path | sed -e 's/^library.path=\"\(.*\)\"/\1/'`
-    LIBRARY_PATH="${LIBRARY_PATH_HOME:-$LIBRARY_PATH}"
-    LIBRARY_URL_HOME=`cat ~/.cilo | grep library.url | sed -e 's/^library.url=\"\(.*\)\"/\1/'`
-    LIBRARY_URL="${LIBRARY_URL_HOME:-$LIBRARY_URL}"
-    SERVER_URL_HOME=`=cat ~/.cilo | grep server.url | sed -e 's/^server.url=\"\(.*\)\"\"/\1`
-    SERVER_URL_"${SERVER_URL_HOME:-$SERVER_URL}"
-fi    
+# VERBOSE="false"
+# INTERACTIVE="true"
+# VVV="false"
+# LOGGING="false"
+# LOGGING_DIRECTORY="log/"
+# DOCKER_SOCKET="/var/run/docker.sock"
+# DOCKER_REGISTRY_URL=""
+# DOCKER_IMAGE_NAME="cilo"
+# LIBRARY_PATH="lib/"
+# LIBRARY_URL=""
+# CREDENTIAL_SERVER_URL=""
 
-if [ -f ".cilo" ]; then
-    PROJECT_NAME_LOCAL=`cat .cilo | grep project.name | sed -e 's/^project.name=\"\(.*\)\"/\1/'`
-    PROJECT_NAME="${PROJECT_NAME_LOCAL:-$PROJECT_NAME}"
-    LOGGING_DIR_LOCAL=`cat .cilo | grep logging.directory | sed -e 's/^logging.directory=\"\(.*\)\"/\1/'`
-    LOGGING_DIR="${LOGGING_DIR_LOCAL:-$LOGGING_DIR}"
-    DOCKER_SOCKET_LOCAL=`cat .cilo | grep docker.socket | sed -e 's/^docker.socket=\"\(.*\)\"/\1/'`
-    DOCKER_SOCKET="${DOCKER_SOCKET_LOCAL:-$DOCKER_SOCKET}"
-    REGISTRY_URL_LOCAL=`cat .cilo | grep docker.registry | sed -e 's/^docker.registry=\"\(.*\)\"/\1/'`
-    REGISTRY_URL="${REGISTRY_URL_LOCAL:-$REGISTRY_URL}"
-    IMAGE_NAME_LOCAL=`cat .cilo | grep docker.image_name | sed -e 's/^docker.image_name=\"\(.*\)\"/\1/'`
-    IMAGE_NAME="${IMAGE_NAME_LOCAL:-$IMAGE_NAME}"
-    LIBRARY_PATH_LOCAL=`cat .cilo | grep library.path | sed -e 's/^library.path=\"\(.*\)\"/\1/'`
-    LIBRARY_PATH="${LIBRARY_PATH_LOCAL:-$LIBRARY_PATH}"
-    LIBRARY_URL_LOCAL=`cat .cilo | grep library.url | sed -e 's/^library.url=\"\(.*\)\"/\1/'`
-    LIBRARY_URL="${LIBRARY_URL_LOCAL:-$LIBRARY_URL}"
-    SERVER_URL_LOCAL=`cat .cilo | grep server.url | sed -e 's/^server.url=\"\(.*\)\"/\1/'`
-    SERVER_URL="${SERVER_URL_LOCAL:-$SERVER_URL}"
-fi
+getProperty() {
+    cat $1 | grep -i $2 | cut -d'=' -f2- | tr -d '"' | tr -d ' '
+}
+
+getPropertiesFromFile() {
+    local PROP_FILE="$1"
+    if [ -f "$PROP_FILE" ]; then
+        var=(); var=`getProperty "$PROP_FILE" "INTERACTIVE"`;           INTERACTIVE="${var:-$INTERACTIVE}"
+        var=(); var=`getProperty "$PROP_FILE" "VERBOSE"`;               VERBOSE="${var:-$VERBOSE}"
+        var=(); var=`getProperty "$PROP_FILE" "VVV"`;                   VVV="${var:-$VVV}"
+        var=(); var=`getProperty "$PROP_FILE" "LOGGING"`;               LOGGING="${var:-$LOGGING}"
+        var=(); var=`getProperty "$PROP_FILE" "LOGGING_DIRECTORY"`;     LOGGING_DIRECTORY="${var:-$LOGGING_DIRECTORY}"
+        var=(); var=`getProperty "$PROP_FILE" "DOCKER_SOCKET"`;         DOCKER_SOCKET="${var:-$DOCKER_SOCKET}"
+        var=(); var=`getProperty "$PROP_FILE" "DOCKER_REGISTRY_URL"`;   DOCKER_REGISTRY_URL="${var:-$DOCKER_REGISTRY_URL}"
+        var=(); var=`getProperty "$PROP_FILE" "DOCKER_IMAGE_NAME"`;     DOCKER_IMAGE_NAME="${var:-$DOCKER_IMAGE_NAME}"
+        var=(); var=`getProperty "$PROP_FILE" "LIBRARY_PATH"`;          LIBRARY_PATH="${var:-$LIBRARY_PATH}"
+        var=(); var=`getProperty "$PROP_FILE" "LIBRARY_URL"`;           LIBRARY_URL="${var:-$LIBRARY_URL}"
+        var=(); var=`getProperty "$PROP_FILE" "CREDENTIAL_SERVER_URL"`; CREDENTIAL_SERVER_URL="${var:-$CREDENTIAL_SERVER_URL}"
+    fi
+}
+
+getProperties() {
+    getPropertiesFromFile "$PWD/.cilo"
+    getPropertiesFromFile "~/.cilo"
+}
+
 
 while [[ $# -gt 0 ]]
 do
@@ -155,7 +157,7 @@ do
             shift; shift;
             ;;
         -s|--server)
-            SERVER_URL="$2"
+            CREDENTIAL_SERVER_URL="$2"
             shift; shift
             ;;
         --log)
@@ -163,7 +165,7 @@ do
             shift;
             ;;
         --log-directory)
-            LOGGING_DIR="$2"
+            LOGGING_DIRECTORY="$2"
             shift; shift;
             ;;
         --interactive)
@@ -175,12 +177,11 @@ do
             shift;
             ;;
         --i|--image)
-            IMAGE_NAME="$2"
+            DOCKER_IMAGE_NAME="$2"
             shift; shift
             ;;
         -r|--registry)
-            REGISTRY_URL="$2"
-            CUSTOM_REGISTRY="true"
+            DOCKER_REGISTRY_URL="$2"
             shift; shift;
             ;;
         *)
@@ -200,24 +201,26 @@ getDateTimeString() {
     date +"%m-%d-%Y-%H-%M-%S" | tr -d '\n\r' | tr -d '\r\n' | tr -d '\n' | tr -d ' '
 }
 
+if [ -z ${PIPELINE+1} ]; then
+    showUsage
+    exit 1;
+fi
+
 if $SHOW_VERSION; then
     printf "%s\n" "$VERSION_STRING"
     exit 0
 fi
-if [ -z ${PIPELINE+x} ]; then
-    PIPELINE="pipeline"
-fi
 INITIAL_TIME=`getDateTimeString`
-LOGGING_FILE="$PWD/$LOGGING_DIR""cilo-""$INITIAL_TIME.txt"
+LOGGING_FILE="$PWD/$LOGGING_DIRECTORY""cilo-""$INITIAL_TIME.txt"
 if $LOGGING; then
-    if ! [ -d "$PWD/$LOGGING_DIR" ]; then
-        mkdir -p "$PWD/$LOGGING_DIR" 1> /dev/null 2> /dev/null
+    if ! [ -d "$PWD/$LOGGING_DIRECTORY" ]; then
+        mkdir -p "$PWD/$LOGGING_DIRECTORY" 1> /dev/null 2> /dev/null
         if ! [ "$(($?))" -eq "0" ]; then
-            printf "%s\n" "Logging failed to initialize. Could not create directory ($LOGGING_DIR)."
+            printf "%s\n" "Logging failed to initialize. Could not create directory ($LOGGING_DIRECTORY)."
             exit 1
         fi
         if ! [ "$?" -eq "0" ]; then
-            printf "%s\n" "Logging failed to initialize. Directory malformed ($LOGGING_DIR)."
+            printf "%s\n" "Logging failed to initialize. Directory malformed ($LOGGING_DIRECTORY)."
             exit 1
         fi
     fi
@@ -309,21 +312,20 @@ if $LOGGING; then
     fi
 fi
 if $VERBOSE; then
-    info "PROJECT_NAME     = %s\n" "${PROJECT_NAME}"
-    info "INTERACTIVE      = %s\n" "${INTERACTIVE}"
-    info "PWD              = %s\n" "${PWD}"
-    info "VERBOSE          = %s\n" "${VERBOSE}"
-    info "VVV              = %s\n" "${VERBOSE}"
-    info "SHOW_VERSION     = %s\n" "${SHOW_VERSION}"
-    info "DOCKER_SOCKET    = %s\n" "${DOCKER_SOCKET}"
-    info "LIBRARY_PATH     = %s\n" "${LIBRARY_PATH}"
-    info "SERVER_URL       = %s\n" "${SERVER_URL}"
-    info "LOGGING          = %s\n" "${LOGGING}"
-    info "LOGGING_DIR      = %s\n" "${LOGGING_DIR}"
-    info "IMAGE_NAME       = %s\n" "${IMAGE_NAME}"
-    info "REGISTRY_URL     = %s\n" "${REGISTRY_URL}"
-    info "CUSTOM_REGISTRY  = %s\n" "${CUSTOM_REGISTRY}"
-    info "PIPELINE         = " ""
+    info "PROJECT_NAME           = %s\n" "${PROJECT_NAME}"
+    info "INTERACTIVE            = %s\n" "${INTERACTIVE}"
+    info "PWD                    = %s\n" "${PWD}"
+    info "VERBOSE                = %s\n" "${VERBOSE}"
+    info "VVV                    = %s\n" "${VERBOSE}"
+    info "SHOW_VERSION           = %s\n" "${SHOW_VERSION}"
+    info "DOCKER_SOCKET          = %s\n" "${DOCKER_SOCKET}"
+    info "LIBRARY_PATH           = %s\n" "${LIBRARY_PATH}"
+    info "CREDENTIAL_SERVER_URL  = %s\n" "${CREDENTIAL_SERVER_URL}"
+    info "LOGGING                = %s\n" "${LOGGING}"
+    info "LOGGING_DIRECTORY      = %s\n" "${LOGGING_DIRECTORY}"
+    info "DOCKER_IMAGE_NAME      = %s\n" "${DOCKER_IMAGE_NAME}"
+    info "DOCKER_REGISTRY_URL    = %s\n" "${DOCKER_REGISTRY_URL}"
+    info "PIPELINE               = " ""
     for COMMAND in "${PIPELINE[@]}"; do
         log "%s " "$COMMAND"
     done
@@ -443,7 +445,7 @@ doCommandsExist() {
 }
 
 runProject() {
-    local imageName="$IMAGE_NAME"
+    local imageName="$DOCKER_IMAGE_NAME"
     if ! dockerHasImage "$imageName"; then
         dockerCreateImage "$imageName"
         if ! dockerHasImage "$imageName"; then
@@ -468,7 +470,7 @@ curl
 jq
 EOF`
 doCommandsExist "$dependencies"
-
+getProperties
 validateDocker
 runProject
 
